### 1. Write code to create a 4x3 matrix with values ranging from 2 to 13. 

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(2,13,12).reshape(4,3)
arr

array([[12,  9,  3],
       [11, 10,  8],
       [ 6, 11, 11],
       [ 5,  7, 12]])

### 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20) 

In [7]:
arr2 =np.random.randint(1,50,20)
arr2



array([44,  5,  4,  2,  3, 10, 27, 35, 39, 14, 38, 31, 47, 10, 42, 21, 38,
       29, 42, 41])

In [8]:
np.where(arr2 % 2 != 0,-1,arr2)

array([44, -1,  4,  2, -1, 10, -1, -1, -1, 14, 38, -1, -1, 10, 42, -1, 38,
       -1, 42, -1])

### 3.  Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999. 
a. Create a 1d-array of mobile phones prices 
b. Convert this array to float type 
c. Append a new mobile having price of 13999 Rs. to this array 
d. Reverse this array of mobile phones prices 
e. Apply GST of 18% on mobile phones prices and update this array. 
f. 
Sort the array in descending order of price 
g. What is the average mobile phone price 
h. What is the difference b/w maximum and minimum price

In [13]:
# a. Create a 1d-array of mobile phones prices

arr3 = np.array([ 6999, 7500 ,11999, 27899, 14999, 9999])
arr3

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [31]:
# b. Convert this array to float type

arr4 = np.asfarray(arr3)
arr4

arr4.dtype

dtype('float64')

In [32]:
arr5 = arr3.astype(float)
arr5.dtype

dtype('float64')

In [38]:
# c. Append a new mobile having price of 13999 Rs. to this array

np.append(arr3,13999)

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [40]:
#d . Reverse this array of mobile phones prices 

arr3[::-1]


array([ 9999, 14999, 27899, 11999,  7500,  6999])

In [41]:
#e . Apply GST of 18% on mobile phones prices and update this array.

arr3

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [44]:
arr7 = arr3 + (arr3 * 0.18 )

arr7

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82])

In [46]:
#f Sort the array in descending order of price.

arr8 = np.sort(arr3)[::-1]
arr8

array([27899, 14999, 11999,  9999,  7500,  6999])

In [51]:
# What is the average mobile phone price 


arr9 = arr3.mean()
arr9

13232.5

In [52]:
#What is the difference b/w maximum and minimum price 

arr10 = arr3.max()
arr11 = arr3.min()

arr10 - arr11

20900

In [57]:
#  Find out the indices of non zero element in given array  [1,2,0,0,4,0] 

arr12 =np.array([1,2,0,0,4,0])

arr13 = np.where(arr12==0)
arr13

(array([2, 3, 5], dtype=int64),)