# Numpy

In [59]:
import numpy as np

In [60]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [61]:
arr2 = np.array([15,52,34,40])
arr2

array([15, 52, 34, 40])

In [62]:
arr3 = arr1 + arr2
arr3

array([16, 54, 37, 44])

In [63]:
# arr1 = arr1 * 4
# arr1

In [64]:
arr1 < arr2 

array([ True,  True,  True,  True])

In [65]:
arr1.dtype

dtype('int32')

## Time Complexity

In [66]:
%%time

list1 = [ i for i in range(1,10001)]
list2 = [ i for i in range(10001,20001)]
list3 = []

for i in range(len(list1)):
    list3.append(list1[i] + list2[i])
    

CPU times: total: 0 ns
Wall time: 3.52 ms


In [67]:
%%time

arr1 = np.array([ i for i in range(1,10001)])
arr2 = np.array([ i for i in range(10001,20001)])
arr3 = arr1 + arr2

CPU times: total: 15.6 ms
Wall time: 3 ms


# Memory size Comaprison

In [68]:
list1 = [1,2,3,4]
arr2 = np.array(list1)
arr2

array([1, 2, 3, 4])

In [69]:
import sys

In [70]:
sys.getsizeof(list1[0])

28

In [71]:
sys.getsizeof(list[0])*len(list1)

320

In [72]:
arr2.itemsize * arr2.size

16

# way to create array

In [73]:
arr1 = np.array((10,20,30,40))
arr1

array([10, 20, 30, 40])

In [74]:
arr = np.array({10,20,30,40})
arr

array({40, 10, 20, 30}, dtype=object)

In [75]:
arr = np.array({"a":20,"b":40})
arr

array({'a': 20, 'b': 40}, dtype=object)

In [76]:
arr1.shape

(4,)

# Multidimension array 

In [77]:
data = np.array([[1,2,3,5],[4,5,7,8]])
data.shape

(2, 4)

In [78]:
data = np.array([[1,2,3],[4,8,9],[4,5,7]])
data.shape
# data

(3, 3)

In [79]:
data = np.array([[[1,2],[4,8]],[[1,2],[4,8]]])
data.shape

(2, 2, 2)

In [80]:
arr2 = np.linspace(21,85,10)
arr2

array([21.        , 28.11111111, 35.22222222, 42.33333333, 49.44444444,
       56.55555556, 63.66666667, 70.77777778, 77.88888889, 85.        ])

# Random variables 

In [81]:
arr1 = np.random.randint(1000,1500,25)
arr1

array([1357, 1431, 1188, 1482, 1222, 1382, 1261, 1048, 1299, 1274, 1320,
       1288, 1287, 1017, 1133, 1067, 1224, 1418, 1471, 1311, 1368, 1455,
       1412, 1297, 1199])

In [82]:
arr3 = np.random.rand(6,3)
arr3 

array([[0.34298309, 0.70573421, 0.20866525],
       [0.19318512, 0.18637066, 0.46411908],
       [0.54648778, 0.37546924, 0.82233923],
       [0.49334087, 0.96903377, 0.29965418],
       [0.33344213, 0.56750807, 0.86188063],
       [0.6668912 , 0.60682936, 0.61826728]])

In [83]:
arr4 = np.random.randn(3,3)
arr4

array([[-2.64745468,  1.19199028,  0.05802481],
       [ 1.06598836, -1.09735844,  0.34743835],
       [-0.47548006,  1.08764404,  1.29225305]])

# Functions in Array

In [84]:
arr1 = np.array([6,7,8,5])
arr2 = np.array([6,7])

arr4 = np.pad(arr2,pad_width=(0,2))
arr4

array([6, 7, 0, 0])

In [85]:
arr1.reshape(4)

array([6, 7, 8, 5])

In [86]:
arr1.min()

5

In [87]:
arr1 = np.array([6,7,8,5,7,8,9,10])


In [88]:
arr1.min()

5

In [89]:
arr1.max()

10

In [90]:
arr1.mean()

7.5

# 

In [103]:
arr = np.random.randint(100,150,25).reshape(5,5)
arr

array([[142, 122, 128, 134, 127],
       [132, 146, 134, 126, 132],
       [104, 141, 108, 104, 140],
       [144, 102, 117, 145, 130],
       [109, 122, 128, 114, 119]])

In [92]:
arr[0]

array([130, 114, 125, 139, 131])

In [93]:
arr[2,3]

134

In [94]:
arr[0:2]

array([[130, 114, 125, 139, 131],
       [113, 105, 118, 128, 131]])

In [101]:
arr[0:3:2]

array([[130, 114, 125, 139, 131],
       [121, 125, 100, 134, 126]])

In [96]:
arr[1,0:5]

array([113, 105, 118, 128, 131])

In [97]:
arr[1]

array([113, 105, 118, 128, 131])

In [98]:
arr[1:2]

array([[113, 105, 118, 128, 131]])

In [99]:
arr[1,:]

array([113, 105, 118, 128, 131])

In [102]:
arr[0:4:-1]

array([], shape=(0, 5), dtype=int32)

In [108]:
result = np.array{[arr[i,i] for i in range(0,5)]}

SyntaxError: invalid syntax (3536719732.py, line 1)

In [117]:
age = np.array([45,60,-11,0,100,451,74,20,-45,651])

In [119]:
age[(age<0) | (age>100)]

array([-11, 451, -45, 651])

In [116]:
age = np.array([45,60,-11,0,100,451,74,20,-45,651])

age[np.where((age < 0 | age > 100))]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()